export const C = {
  bg:           '#f0eef8',
  card:         '#ffffff',
  cardBorder:   '#e5e0f5',
  primary:      '#7c3aed',
  primaryLight: '#ede9fe',
  primaryText:  '#5b21b6',
  text:         '#1a1a2e',
  textSub:      '#6b7280',
  textMuted:    '#9ca3af',
  green:        '#16a34a',
  greenBg:      '#dcfce7',
  red:          '#dc2626',
  redBg:        '#fee2e2',
  orange:       '#ea580c',
  orangeBg:     '#ffedd5',
  blue:         '#2563eb',
  blueBg:       '#dbeafe',
  navBg:        '#ffffff',
  navBorder:    '#e5e0f5',
  tabActive:    '#7c3aed',
  tabInactive:  '#9ca3af',
  inputBg:      '#f9f7ff',
  inputBorder:  '#d8d0f0',
};